<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
	  <TargetFramework>net10.0</TargetFramework>
	  <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Yosoku.Trainer-0d35575a-c72a-4fd1-868f-6708b5b83969</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageReference Include="Microsoft.ML" Version="5.0.0" />
    <PackageReference Include="Microsoft.ML.LightGbm" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Yosoku.Data\Yosoku.Data.csproj" />
  </ItemGroup>
</Project>
