// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yosoku.Data;

#nullable disable

namespace Yosoku.Data.Migrations
{
    [DbContext(typeof(YosokuContext))]
    [Migration("20260816004026_AddSma")]
    partial class AddSma
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Yosoku.Data.Entities.Record", b =>
                {
                    b.Property<string>("Ticker")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<float>("PeRatio")
                        .HasColumnType("float");

                    b.Property<float>("Rsi")
                        .HasColumnType("float");

                    b.Property<float>("Score")
                        .HasColumnType("float");

                    b.Property<float>("Sma200")
                        .HasColumnType("float");

                    b.Property<float>("Sma50")
                        .HasColumnType("float");

                    b.HasKey("Ticker", "Date");

                    b.ToTable("Records");
                });
#pragma warning restore 612, 618
        }
    }
}
